// <auto-generated />
using System;
using BackendU2W.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendU2W.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230302175924_CreacionTablaObjetivosDB")]
    partial class CreacionTablaObjetivosDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendU2W.Models.Objetivos", b =>
                {
                    b.Property<int>("id_obj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_obj"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<int>("id_usu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_obj");

                    b.HasIndex("id_usu");

                    b.ToTable("Tbl_Objetivos");

                    b.HasData(
                        new
                        {
                            id_obj = 1,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            descripcion = "Este es el objetivo1",
                            duracion = 0,
                            id_usu = 1,
                            nombre = "Objetivo1"
                        },
                        new
                        {
                            id_obj = 2,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            duracion = 1,
                            id_usu = 1,
                            nombre = "Objetivo2"
                        },
                        new
                        {
                            id_obj = 3,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            duracion = 1,
                            id_usu = 3,
                            nombre = "Objetivo3"
                        },
                        new
                        {
                            id_obj = 4,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            duracion = 2,
                            id_usu = 4,
                            nombre = "Objetivo4"
                        });
                });

            modelBuilder.Entity("BackendU2W.Models.Usuarios", b =>
                {
                    b.Property<int>("id_usu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usu"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<string>("nick")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_usu");

                    b.ToTable("Tbl_Usuarios");

                    b.HasData(
                        new
                        {
                            id_usu = 1,
                            active = true,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            level = 0,
                            nick = "Usuario1",
                            password = "12345",
                            picture = "a"
                        },
                        new
                        {
                            id_usu = 2,
                            active = false,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            level = 10,
                            nick = "Usuario2",
                            password = "12345",
                            picture = "a"
                        },
                        new
                        {
                            id_usu = 3,
                            active = false,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            level = 20,
                            nick = "Usuario3",
                            password = "12345",
                            picture = "a"
                        },
                        new
                        {
                            id_usu = 4,
                            active = true,
                            create_date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            delete_date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            level = 30,
                            nick = "Usuario4",
                            password = "12345",
                            picture = "a"
                        });
                });

            modelBuilder.Entity("BackendU2W.Models.Objetivos", b =>
                {
                    b.HasOne("BackendU2W.Models.Usuarios", "usuario")
                        .WithMany("Objetivos")
                        .HasForeignKey("id_usu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("BackendU2W.Models.Usuarios", b =>
                {
                    b.Navigation("Objetivos");
                });
#pragma warning restore 612, 618
        }
    }
}
